config/routes.rb
EesportsNet::Application.routes.draw do
  devise_for :users

  root :to => "portal#index"
  resources :portal, :only => :index
  resources :events
  resources :tournaments do
    get 'signup', :to => 'tournaments/participations#create'
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :title, :body
end

app/models/games.rb
class Games < ActiveRecord::Base
	has_many :tournaments
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  belongs_to :game
  belongs_to :event
  has_many :tournament_participations, :class_name => 'Tournament::Participation'
  has_many :users, :through => :tournament_participations
  has_many :matches

  def open?
    #check if tournament is open
    return (self.signup_opens_at < Time.now and self.signup_closes_at > Time.now and
            self.users.count < self.max_participants)  
  end
end

app/models/tournament/match.rb
class Tournament::Match < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :participant_1, :class_name => 'TournamentParticipant'
  belongs_to :participant_2, :class_name => 'TournamentParticipant'
  belongs_to :winner, :class_name => 'TournamentParticipant'
end

app/models/tournament/participation.rb
class Tournament::Participation < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_many :tournament_participations
  has_many :tournaments, :through => :tournament_participations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @event = Event.first
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to(edit_event_url(@event), :flash => {:success => 'Event was successfully created.'} )
    else
      render(:action => 'new')
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to(edit_event_url(@event), :flash => {:success => 'Event was successfully updated.'} )
    else
      render(:action => 'edit')
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
end

app/controllers/tournaments/participations_controller.rb
class Tournaments::ParticipationsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @tournament = Tournament.find(params[:tournament_id])
    @participation = Tournament::Participation.find_by_tournament_id_and_user_id(params[:tournament_id], current_user.id)

    if @participation.present?
      redirect_to(tournament_url(params[:tournament_id]), :flash => {:error => 'You already signed up'} )
    elsif !@tournament.open?
      redirect_to(tournament_url(params[:tournament_id]), :flash => {:error => 'This tournament is not open for sign up'} )
    else
      @participation = Tournament::Participation.new(:tournament => @tournament, :user_id => current_user.id)     
      if @participation.save
        redirect_to(tournament_url(params[:tournament_id]), :flash => {:success => 'You successfully signed up'} )
      else
        redirect_to(tournament_url(params[:tournament_id]), :flash => {:error => 'An error occured while signing up'} )
      end
    end
  end

  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy
    redirect_to tournaments_url
  end

  def signup
    @tournament = Tournament.find(params[:id])
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @tournaments = Tournament.all
    @participations = Tournament::Participation.all
  end

  def show
    @tournament = Tournament.find(params[:id])
  end

  def new
    @tournament = Tournament.new
  end

  def edit
    @tournament = Tournament.find(params[:id])
  end

  def create
    @tournament = Tournament.new(params[:tournament])
    if @tournament.save
      redirect_to(edit_tournament_url(@tournament), :flash => {:success => 'Tournament was successfully created.'} )
    else
      render(:action => 'new')
    end
  end

  def update
    @tournament = Tournament.find(params[:id])
    if @tournament.update_attributes(params[:tournament])
      redirect_to(edit_tournament_url(@tournament), :flash => {:success => 'Tournament was successfully updated.'} )
    else
      render(:action => 'edit')
    end
  end

  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy
    redirect_to tournaments_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tournament_helper.rb
module TournamentHelper
  def generate_bracket(t)
    table_html = "<table>\n"

    table_rows = t.max_participants
    table_cols = Math.log(t.max_participants, 2).ceil
    
    logger.debug "Rows: #{table_rows}\nCols: #{table_cols}\n"
    
    1.upto(table_rows) do |row_num|
      table_html << "  <tr class=\"r#{row_num}\">\n"
      1.upto(table_cols) do |col_num|
        matches_num = (table_rows.to_f**(1/col_num.to_f)).ceil
        if row_num <= matches_num
          table_html << "    <td class=\"c#{col_num}\" style=\"background: #f00\">Match</td>\n"
        else
          table_html << "    <td class=\"c#{col_num}\" >x</td>\n"
        end
      end

      table_html << "  </tr>\n"

    end
    table_html << "</table>\n"
  end
end

app/views/events/_form.html.haml
= form_for(@event) do |f|
  -if @event.errors.any?
    %ul.error
      - @event.errors.full_messages.each do |msg|
        %li= msg
  %div.field
    = f.label(:title)
    %br
    = f.text_field(:title, :class => 'title')
  %div.field
    = f.label(:body)
    %br
    = f.text_area(:body)
  %div.actions
    = f.submit

app/views/events/edit.html.haml
%h1 Edit Event '#{@event.title}'
= render('form')
=link_to("&laquo;Back".html_safe, event_path(@event))

app/views/events/index.html.haml
%section
  - if @events.any?
    - @events.each do |event|
      %article
        %header
          %h1= link_to(event.title, event)
        %div= raw(event.body)
  - else
    %p No events found.
  =link_to("New Event", new_event_path)

app/views/events/new.html.haml
%h1 New Event
= render('form')
=link_to("&laquo;Back".html_safe, events_path)

app/views/events/show.html.haml
%section
  %article
  %header
    %h1= @event.title
  %div= raw(@event.body)
  =link_to("&laquo;Back".html_safe, events_path)
  |
  =link_to('Edit', edit_event_path(@event))

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title European E-sports
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %div.container
      - flash.each do |type, msg|
        %p{:class => type}= msg
      %div.span-20
        = yield
      %div.span-4.last
        - if user_signed_in?
          = link_to "Sign out", destroy_user_session_path, :method => :delete
        - else
          = link_to "Sign in", user_session_path
          or
          = link_to "Sign up", user_registration_path

app/views/tournaments/_form.html.haml
= form_for(@tournament) do |f|
  -if @tournament.errors.any?
    %ul.error
      - @tournament.errors.full_messages.each do |msg|
        %li= msg
  %div.field
    = f.label(:title)
    %br
    = f.text_field(:title, :class => 'title')
  %div.field
    = f.label(:description)
    %br
    = f.text_area(:description)
  %div.field
    = f.label(:signup_opens_at)
    %br
    = f.text_field(:signup_opens_at)
  %div.field
    = f.label(:signup_closes_at)
    %br
    = f.text_field(:signup_closes_at)
  %div.field
    = f.label(:min_participants)
    %br
    = f.text_field(:min_participants)
  %div.field
    = f.label(:max_participants)
    %br
    = f.text_field(:max_participants)
  %div.actions
    = f.submit

app/views/tournaments/edit.html.haml
%h1 Edit Event '#{@tournament.title}'
= render('form')
=link_to("&laquo;Back".html_safe, tournament_path(@tournament))

app/views/tournaments/index.html.haml
%section
  - if @participations.any?
    %ul
      - @participations.each do |participation|
        %li #{participation.user.name} signed up for #{link_to(participation.tournament.title, participation.tournament)} - #{time_ago_in_words(participation.updated_at)} ago
  - if @tournaments.any?
    - @tournaments.each do |tournament|
      %article
        %header
          %h1= link_to(tournament.title, tournament)
          %p= link_to('Sign up', tournament_signup_path(tournament))
        %div= raw(tournament.description)
  - else
    %p No tournaments found.
  %hr
  =link_to("New Tournament", new_tournament_path)

app/views/tournaments/new.html.haml
%h1 New Tournament
= render('form')
=link_to("&laquo;Back".html_safe, tournaments_path)

app/views/tournaments/show.html.haml
%section
  %article
  %header
    %h1= @tournament.title
    %p= link_to('Sign up', tournament_signup_path(@tournament))
  %div= raw(@tournament.description)
  %hr
  %div
    %div#treewrap
      %canvas#tree
    - if @tournament.matches.any?
      %ul
        - @tournament.matches.each do |match|
          %li= match.inspect
  %div
    - if @tournament.users.any?
      %ul
        - @tournament.users.each do |user|
          %li= user.name
    - else
      There are no participants
  %hr
  =link_to("&laquo;Back".html_safe, tournaments_path)
  |
  =link_to('Edit', edit_tournament_path(@tournament))